### ISSUE TITLE
Feature request: Support secrets.yaml in .devcontainer folder

### ISSUE THREAD

**Issue by msvinth** [ludeeus/devcontainer#1]
I am using your very nice devcontainer and is developing an integration which needs credentials. In this case it would be nice if there was support for adding secrets.yaml in the .devcontainer folder so !secret could be used in configuration.yaml.

**Comment by ludeeus** [comment]
This is designed for development, IMO it makes no sense to put that in a separate file in a dev environment.
I will not block a PR that adds it, but I will not add it myself.

**Comment by msvinth** [comment]
Yes I do understand this is for development. 
The scenario I had I mind was to check in a working configuration.yaml with git ignore secrets.yaml. Basically just an easy way to not leak any contributors working credentials.

I will create a PR.
